name: Run Snyk Scan for Package Vulnerabilities for sre-example-apps
'on': push
jobs:
  snyk-scan-go:
    permissions:
      contents: read
      id-token: write
    uses: epidemicsound/github-workflows/.github/workflows/snyk-scan-go.yaml@main
  snyk-scan-node:
    permissions:
      contents: read
      id-token: write
    uses: epidemicsound/github-workflows/.github/workflows/snyk-scan-node.yaml@main
